"""Chapter 20 authored written artifacts, extending the shared response model."""

from soft_skills_lab.domain.models import (MessagePurpose, Participant, ProfessionalResponse, ReviewIntent,
    RiskLevel, StatusCategory, WorkplaceScenario, WrittenChannel, WrittenMessage)


def message(*, channel=WrittenChannel.CHAT, purpose=MessagePurpose.INFORM, purpose_statement="Make deployment risk and next decision visible.",
            context=(), state=None, facts=(), uncertainty=(), impact=(), request=None, decision=None, action=None,
            owner=None, due=None, detail=(), follow_up=None, standalone=False, appropriate=True, durable=False,
            acknowledgement=False, urgency=True, review_intent=None, correction=False, topic="Decision needed: T6 migration risk",
            audience=("Morgan", "Jordan")):
    return WrittenMessage("Alex", audience, channel, topic, purpose, purpose_statement, context, state, facts,
        uncertainty, impact, request, decision, action, owner, due, detail, (), follow_up, review_intent,
        standalone, appropriate, durable, acknowledgement, urgency, correction)


BASE=dict(context=("T6 deployment", "Jordan depends on the release"), state=StatusCategory.AT_RISK,
    facts=("Large-table migration lock test remains above the acceptable window.",),
    uncertainty=("A lower-lock approach may bring duration inside the limit.",),
    impact=("Production is unaffected now.", "Jordan's T6 dependency may move."),
    action="Test a lower-lock migration approach", owner="Alex", due="T5",
    decision="Move the release if lock duration remains unsafe", follow_up="T5", standalone=True)

RESPONSES={
 "context-free":ProfessionalResponse("context-free","Context-free","Migration issue. Looking into it.",written_message=message(action="Investigate migration",owner="Alex")),
 "activity-only":ProfessionalResponse("activity-only","Activity only","I've been testing the migration, reviewing logs, running staging, and trying query changes.",written_message=message(context=("Migration testing",),facts=("Tests and log review occurred.",),detail=("logs","staging","query changes"))),
 "alarm-without-evidence":ProfessionalResponse("alarm-without-evidence","Alarm without evidence","The deployment is probably going to fail.",exceeds_available_evidence=True,written_message=message(context=("T6 deployment",),state=StatusCategory.BLOCKED,urgency=False)),
 "false-reassurance":ProfessionalResponse("false-reassurance","False reassurance","Everything should be fine.",unsupported_promise=True,written_message=message(context=("T6 deployment",),state=StatusCategory.ON_TRACK,urgency=False)),
 "wall-of-text":ProfessionalResponse("wall-of-text","Wall of text","Full SQL, logs, implementation detail, and chronology precede a buried note that lock duration may affect T6.",written_message=message(context=BASE["context"],state=StatusCategory.AT_RISK,facts=BASE["facts"],request="Review if needed",detail=("full SQL","complete logs","implementation chronology"),appropriate=False)),
 "ambiguous-request":ProfessionalResponse("ambiguous-request","Ambiguous request","T6 is at risk because the lock test is high. Production is unaffected. Morgan, can you advise?",written_message=message(**BASE,request="Morgan, can you advise?",purpose=MessagePurpose.REQUEST)),
 "decision-useful":ProfessionalResponse("decision-useful","Decision-useful written update","T6 deployment is at risk, not blocked. The large-table lock test remains high; production is unaffected. I'm testing a lower-lock approach through T5. If unsafe, I'll recommend moving the release. Jordan, your dependency may shift. I'll update you both at T5.",material_risk_communicated=True,preserves_uncertainty=True,dependency_acknowledged=True,follow_up_point=5,written_message=message(**BASE,request="Morgan: decide at T5 whether to move T6 if the test remains unsafe",purpose=MessagePurpose.REQUEST)),
 "concise-decision-useful":ProfessionalResponse("concise-decision-useful","Concise decision-useful update","T6 is at risk: the large-table lock test is still high; production is unchanged. I'm testing a safer approach by T5, then Morgan may need to move the release. Jordan's dependency may shift. Next update: T5.",material_risk_communicated=True,preserves_uncertainty=True,dependency_acknowledged=True,follow_up_point=5,written_message=message(**BASE,request="Morgan: decide at T5 whether to move T6 if unsafe",purpose=MessagePurpose.REQUEST)),
}

DEPLOYMENT_RISK=WorkplaceScenario("deployment-risk","Risky deployment written update","Alex must make deployment state legible in team chat.",
 (Participant("Alex","developer"),Participant("Morgan","manager"),Participant("Jordan","dependent teammate")),
 ("Target is T6.","At T4 one large-table lock-duration test is failing.","Production has not changed.","Jordan depends on T6.","Alex can investigate through T5."),
 ("Whether the lower-lock approach will meet the acceptable window.",),(),RiskLevel.HIGH)

ARTIFACTS={
 "release-readiness-recap":message(channel=WrittenChannel.DECISION_RECORD,purpose=MessagePurpose.DOCUMENT,purpose_statement="Preserve the meeting's state change.",topic="Friday release decision",context=("Release-readiness meeting",),decision="Approve Friday release with a 30-day export limit",facts=("The limited scope protects the date boundary.",),action="Implement the 90-day boundary fix",owner="Alex; Priya owns full-scope follow-up",due="T4 checkpoint",standalone=True,durable=True),
 "verification-pr-review":message(channel=WrittenChannel.PR_COMMENT,purpose=MessagePurpose.REVIEW,purpose_statement="Resolve a correctness concern against the verification contract.",topic="Unknown vendor responses must remain retryable",context=("This branch maps unknown vendor responses to permanent failure.",),facts=("The verification contract requires unknown provider states to remain retryable.",),impact=("Members must be able to try again safely.",),request="Can we preserve retryable behavior here?",owner="Alex",review_intent=ReviewIntent.BLOCKING,standalone=True,durable=True),
 "verification-ticket":message(channel=WrittenChannel.TICKET,purpose=MessagePurpose.INFORM,purpose_statement="Let another engineer continue the investigation.",topic="Intermittent verification failure",context=("Reproduced 3 of 20 attempts in staging.",),facts=("Failures share vendor response X17.",),uncertainty=("Retry timing is the current hypothesis, not established cause.",),action="Capture vendor timing and replay fixture",owner="Alex",follow_up="T3",standalone=True,durable=True),
 "api-handoff":message(channel=WrittenChannel.HANDOFF_NOTE,purpose=MessagePurpose.HANDOFF,purpose_statement="Transfer usable endpoint state to Jordan.",topic="Verification endpoint ready for frontend integration",context=("Endpoint and fixtures are ready.",),facts=("Contract v3 and success/error fixtures are linked.",),impact=("Bulk verification remains unsupported.",),request="Jordan: acknowledge the fixtures load before starting integration",owner="Jordan",due="next workday",standalone=True,durable=True,acknowledgement=True),
 "adapter-disagreement":message(channel=WrittenChannel.PR_COMMENT,purpose=MessagePurpose.REVIEW,purpose_statement="Challenge removal with decision-relevant evidence.",topic="Retain and simplify vendor adapter",context=("We should remove abstractions that do not earn their cost.",),facts=("The adapter absorbed two vendor field-name changes without application-service changes.",),request="Simplify the adapter before removing the boundary",review_intent=ReviewIntent.SUGGESTION,standalone=True),
 "security-escalation":message(channel=WrittenChannel.EMAIL,purpose=MessagePurpose.ESCALATE,purpose_statement="Coordinate a possible internal-metadata exposure.",topic="Security owner needed: possible internal metadata exposure",context=("A public error response may include internal metadata.",),facts=("The response path has been disabled.",),uncertainty=("Exposure count and access are not yet known.",),impact=("Internal metadata may have been visible externally.",),request="Security owner: assess exposure and advise notification scope",owner="Security on-call",follow_up="T2",standalone=True,durable=True),
 "material-correction":message(channel=WrittenChannel.CHAT,purpose=MessagePurpose.CONFIRM,purpose_statement="Correct a materially wrong written state.",topic="Correction: T6 is at risk, not blocked",context=("Earlier update incorrectly said blocked.",),state=StatusCategory.AT_RISK,facts=("Implementation can continue.",),impact=("The issue affects release confidence, not current progress.",),standalone=True,correction=True),
 "operations-incident":message(channel=WrittenChannel.EMAIL,purpose=MessagePurpose.INFORM,purpose_statement="Give operations workflow impact and guidance.",topic="Verification workflow incident update",context=("Verification requests intermittently fail.",),facts=("Underlying incident fact: vendor response X17.",),impact=("Affected workflow: member verification.",),action="Use retry guidance until the next update",follow_up="T3",standalone=True),
 "engineering-incident":message(channel=WrittenChannel.CHAT,purpose=MessagePurpose.INFORM,purpose_statement="Coordinate engineering investigation.",topic="Verification X17 investigation",context=("Verification requests intermittently fail.",),facts=("Underlying incident fact: vendor response X17.","Request IDs and staging reproduction are attached."),action="Inspect response timing",follow_up="T3",standalone=True),
 "informational-no-reply":message(channel=WrittenChannel.STATUS_NOTE,purpose=MessagePurpose.INFORM,purpose_statement="Record completed deployment.",topic="Deployment completed",facts=("Deployment completed and checks passed.",),standalone=True,durable=True,acknowledgement=False,audience=("Project channel",)),
 "contract-reply-draft":message(channel=WrittenChannel.CHAT,purpose=MessagePurpose.CONFIRM,purpose_statement="Immediate unsent draft.",topic="Contract reply draft",context=("You should have read the update.",),audience=("Unsent draft",)),
 "contract-reply-final":message(channel=WrittenChannel.CHAT,purpose=MessagePurpose.CONFIRM,purpose_statement="Correct shared contract state and repair the handoff.",topic="T4 contract example clarification",context=("The example changed at T4 and the handoff was not explicit enough.",),facts=("Public field names did not change.","The retryable-state example changed."),action="Resend the current contract and explicitly flag future contract-affecting updates",owner="Alex",standalone=True,durable=True),
 "forwardable-deployment":message(channel=WrittenChannel.EMAIL,purpose=MessagePurpose.INFORM,purpose_statement="Give a new reader enough deployment context.",topic="Decision needed: T6 migration risk",context=BASE["context"],state=StatusCategory.AT_RISK,facts=BASE["facts"],uncertainty=BASE["uncertainty"],impact=BASE["impact"],action=BASE["action"],owner="Alex",due="T5",follow_up="T5",standalone=True,durable=True,audience=("Morgan","Jordan","forwarded decision owner")),
 "low-impact-clarification":message(channel=WrittenChannel.CHAT,purpose=MessagePurpose.REQUEST,purpose_statement="Resolve a non-urgent naming clarification.",topic="Question: fixture name",context=("The fixture name differs between two tests.",),request="Jordan: which established fixture name should this test use?",owner="Jordan",standalone=True,urgency=True,audience=("Jordan",)),
}
